eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order


server:
  port: 1234

logging:
  level:
    com.flysky.study.springcloud.order: debug

