/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 13 07:53:44 GMT 2021
 */

package com.flysky.study.mybatis.dao;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.flysky.study.mybatis.dao.EoaTaskDao;
import com.flysky.study.mybatis.model.EoaTask;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class EoaTaskDao_ESTest extends EoaTaskDao_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EoaTaskDao eoaTaskDao0 = new EoaTaskDao();
      EoaTask eoaTask0 = new EoaTask();
      // Undeclared exception!
      try { 
        eoaTaskDao0.save(eoaTask0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.flysky.study.mybatis.dao.EoaTaskDao", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EoaTaskDao eoaTaskDao0 = new EoaTaskDao();
      // Undeclared exception!
      try { 
        eoaTaskDao0.list();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.flysky.study.mybatis.dao.EoaTaskDao", e);
      }
  }
}
